### ISSUE TITLE
doesn't work if image syntax is switched to html

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-plugin-image-viewer#1]
any chance to provide the desired behaviour if html syntax for images is in use?

**Comment by plylrnsdy** [comment]
It works in Typora 1.9.5 & plugin-core 2.3.20 & image-viewer 1.0.2.

Or you can check whether the plugin is disabled in your settings.

**Comment by thob** [comment]
it's active, I'm on Typora 1.9.3 though (Linux) everything else is like yours. Once I click on an image I only get to view the html code and no magnifier

**Comment by thob** [comment]
hold … it works but only if you do not use any additional tag. I'm using` <figure><img src=""/><figcaption>lorem ipsum</figcaption></figure>`

**Comment by plylrnsdy** [comment]
Please update to 1.0.3. Now you can click `<img>` wrapped in html to open viewer.

**Comment by thob** [comment]
thanks!
